import "./global.css";
import { Button, Paper, buttonGroupClasses } from "@mui/material";
import Image from "next/image";

export const metadata = {
	title: "Game Trucker",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<>
			<html lang="en">
				<body>
					<div style={{ width: "100vw", height: "100vh", position: "relative" }}>
						<Image
							src="/nintendo.jpg"
							alt="Picture of nintendo"
							fill
							style={{ filter: "grayscale(90%) blur(5px)" }}
						/>
						<Paper
							elevation={20}
							sx={{ width: "60%", height: "100%", position: "relative", left: "20%" }}
						>
							{children}
						</Paper>
					</div>
				</body>
			</html>
		</>
	);
}
